# Generated by Django 2.2.6 on 2019-10-14 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='imageurl',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
