# Generated by Django 2.2.6 on 2019-10-14 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191014_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='imageurl',
            new_name='imageurl1',
        ),
        migrations.AddField(
            model_name='item',
            name='imageurl2',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
