# Generated by Django 2.2.7 on 2019-11-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_electronic_grocery_jewelry_phone_tablet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronic',
            name='imageurl1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='imageurl1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='imageurl1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='phone',
            name='imageurl1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='imageurl1',
            field=models.ImageField(upload_to=''),
        ),
    ]
